Repository 2023-Team-Luna-Achieve/project, pull requests merged in 2023-10, with the labels that each got.

#8 [Chore] ESLint 수정
  frontend/.eslintrc.cjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/atom.ts
  frontend/src/main.tsx
Labels: 기타/세팅

#9 [Chore] Router 세팅
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/pages/MainPage.tsx
Labels: 기타/세팅

#13 [Feat] Header 생성 및 Page Routing
  frontend/src/App.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/pages/AboutPage.tsx
  frontend/src/pages/CommunityPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/NoticePage.tsx
Labels: 퍼블리싱

#27 [Feat] Nginx 연동
  .idea/libraries/sbt__org_scala_lang_scala_library_2_12_17_jar.xml
  .idea/modules.xml
  .idea/modules/project-build.iml
  .idea/modules/project.iml
  .idea/modules/project_8879.iml
  .idea/scala_compiler.xml
  .idea/workspace.xml
  backend/nginx/app.conf
  backend/nginx/dockerfile
  backend/nginx/nginx.conf
  backend/src/main/java/backend/backend/auth/controller/EmailController.java
  backend/src/main/java/backend/backend/user/dto/SignUpRequest.java
  docker-compose.yml
  project/target/config-classes/$6ddeed40c15b49e02f43$.class
  project/target/config-classes/$6ddeed40c15b49e02f43.cache
  project/target/config-classes/$6ddeed40c15b49e02f43.class
  target/streams/_global/_global/csrLogger/_global/streams/out
  target/streams/_global/_global/dumpStructure/_global/streams/out
  target/streams/_global/update/_global/streams/out
  target/streams/_global/updateClassifiers/_global/streams/out
  target/streams/_global/updateClassifiers/_global/streams/update_cache_2.12/inputs
  target/streams/_global/updateClassifiers/_global/streams/update_cache_2.12/output
Labels: 기능구현
